name: Push File

on: ['push', 'workflow_dispatch']

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ALT_ACCOUNT }}
      with:
        source_file: 'README.md'
        destination_repo: 'NightmareXIV/.github'
        destination_folder: ''
        user_email: 'noreply@github.com'
        user_name: 'NightmareBot'
